# design-doc circleci config
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/latest

    steps:
      - checkout

      # install sphinx
      - run:
          name: install sphinx
          command: |
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -q sphinx
            pip install -q recommonmark

      # sphinx build
      - run:
          name: test sphinx build
          command: |
            source .venv/bin/activate
            sphinx-build -n -W -T -b html . _build/html
